# Prompts
from .system import (
    SYSTEM_PROMPT, INSIGHTS_PROMPT, RECOMMENDATIONS_PROMPT,
    SYSTEM_PROMPT_V2, INSIGHTS_PROMPT_V2,
    SYSTEM_PROMPTS, INSIGHTS_PROMPTS
)

__all__ = [
    'SYSTEM_PROMPT', 'INSIGHTS_PROMPT', 'RECOMMENDATIONS_PROMPT',
    'SYSTEM_PROMPT_V2', 'INSIGHTS_PROMPT_V2',
    'SYSTEM_PROMPTS', 'INSIGHTS_PROMPTS'
]
